### PR TITLE
first draft of CR September 2024 workshop page

### PR DESCRIPTION
**Pull request by dianaiusan**
Compared to the previous workshop, I added the "Q&A helper" role. Its name and description may be need to be changed.
I added your names in some places, @bast and @rkdarst. Pls. let me know if you disagree.

### CODE REVIEW

**Comment by bast** [comment]
I am happy to contribute to organization but organizers are you and Enrico? Or has this changed?

**Comment by dianaiusan** [comment]
> I am happy to contribute to organization but organizers are you and Enrico? Or has this changed?

It has not changed, but I though you may want credit for all the question answering.

**Comment by dianaiusan** [comment]
@bast, should I remove your name from the organizers list? I will add Enrico's of course.

**Comment by dianaiusan** [comment]
Updated PR with Radovan's name removed and added Enrico's.

**Pull request merged**
